name = "rpt-card"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "rpt-card-db"
database_id = "90074b99-eb35-4ef4-8d34-81c291a3f98b"
